### ISSUE TITLE
ImportError: cannot import name utils

### ISSUE THREAD

**Issue by keteflips** [yadayada/acd_cli#406]
```
root@talyn:~# acd_cli sync
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/bin/acd_cli.py", line 22, in <module>
    from acdcli.api import client
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/client.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python3.2/dist-packages/requests/__init__.py", line 63, in <module>
    from . import utils
ImportError: cannot import name utils
```

**Comment by acs-ferreira** [comment]
Try run:

````
sudo apt-get install build-essential python3 python3-appdirs python3-dateutil python3-requests python3-sqlalchemy python3-pip
````

**Comment by fpabernard** [comment]
Hello

I have the same error trying to install acdcli on Debian wheezy

I'm totalyy knob on python and pip, just wanted to use acdcli.

It works fine on Unbuntu 16.04 xenial

Trying to install on Debian wheezy, I had to use the following commands, sligthly different than these given there : [http://xmodulo.com/access-amazon-cloud-drive-command-line-linux.html](url) 👍 
apt-get install python3-pip
pip-3.2 install --upgrade acdcli
acd_cli init

I have the error signaled by keeflips. Installing the packages listed by acs-ferreira does not help

Thank you for helpin

**Comment by fpabernard** [comment]
On ubuntu, python3 -V says : Python 3.5.2
On debian, python3 -V says : Python 3.2.3
Is there any hope ?

**Comment by yadayada** [comment]
When installing your distribution's version of requests, you should also uninstall the pip version.

**Comment by ifsnop** [comment]
Other option. If:

`# python -c "import utils"`

fails, then maybe utils aren't install. Try:

`# pip install utils`

**Comment by fpabernard** [comment]
Thanks,

I tried on a target system that is not compatible (Debian Wheezy "out of 
the box")

No problem with Debian Jessie or Ubuntu

Best regards

F.Bernard

**Comment by andrewdavidwong** [comment]
Just ran into this on Fedora 24 after installing `acd_cli` from the Fedora repos. The solution was to install `dateutil`, as well:

    sudo dnf install python3-dateutil
